<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.4.0 setup script
 * Date: Sat, 28 Jan 2012 22:22:25 +0800
 */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>